[package]
name = "umd"
version = "0.1.0"
edition = "2021"

[dependencies]
monoio = "0.2.1"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.8.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
