[package]
name = "umd"
version = "0.1.0"
edition = "2021"

[dependencies]
monoio = "0.1.6"
serde = { version = "1.0.171", features = ["derive"] }
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
